urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    url(r'^$',
        view='udoxmailinglist.views.signup',
        name='signup_form'),
    url(r'^mobile/$',
        view='udoxmailinglist.views.mobile_signup',
        name='mobile_signup_form'),
)

models.py
from datetime import datetime
from django.db import models

from udoxcore.models import BaseModel, BaseManager, StatusModel, GENDER_CHOICES


class InterestGroup(StatusModel):
    sort_weight = models.IntegerField(default=100, help_text="'Heavier' groups will sink to the bottom of lists. Items with the same weight will sort alphabetically.")
    title = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        ordering = ["sort_weight","title"]


class InterestItemManager(BaseManager):
    def get_query_set(self):
        return super(InterestItemManager, self).get_query_set().filter(group__status__in=[1,2])

class InterestItem(StatusModel):
    group = models.ForeignKey(InterestGroup, related_name='items', help_text="The item will not appear on site unless its parent group is also Published.")
    sort_weight = models.IntegerField(default=100, help_text="'Heavier' items will sink to the bottom of lists. Items with the same weight will sort alphabetically.")
    title = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)
    
    objects = InterestItemManager()
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        ordering = ["group__pk","sort_weight","title"]


class Member(BaseModel):
    join_date = models.DateTimeField(auto_now_add=True, editable=False, null=False)
    last_modified = models.DateTimeField(auto_now=True, editable=False, null=False)
    last_exported = models.DateTimeField(editable=False, null=True, blank=True)
    name = models.CharField(max_length=128)
    email = models.EmailField(unique=True)
    dob = models.DateField('Date of Birth', blank=True, null=True, default="YYYY-MM-DD")
    sex = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, null=True)
    mobile = models.CharField(max_length=32, blank=True, null=True)
    interest_items = models.ManyToManyField(InterestItem)
    
    def interest_groups(self):
        group_ids = self.interest_items.order_by().values_list('group__pk', flat=True)
        return InterestGroup.objects.filter(pk__in=group_ids)

    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ["name","email"]
        get_latest_by = 'join_date'

views.py
import datetime
from django import forms
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.template.loader import render_to_string
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.forms.extras import widgets
from django.http import Http404, HttpResponse, HttpResponseRedirect

from udoxmailinglist import models
from udoxcore.models import GENDER_CHOICES
from udoxrecaptcha import ReCaptchaField


class SignupForm(forms.ModelForm):
    sex = forms.ChoiceField(widget=forms.RadioSelect, choices=GENDER_CHOICES, required=False)
    now = datetime.datetime.now()
    dob = forms.DateField(widget=widgets.SelectDateWidget(years=range(now.year,1900,-1)), required=False)
    interest_items = forms.ModelMultipleChoiceField(queryset=models.InterestItem.objects.all(), widget=forms.CheckboxSelectMultiple, required=False)
    captcha = ReCaptchaField()

    class Meta:
        model = models.Member


def signup(request):
    status = 200
    if request.method == 'POST':
        form = SignupForm(request.POST, initial={'captcha': request.META['REMOTE_ADDR']})
        if form.is_valid():
            form.save()
            if request.is_ajax():
                template = 'mailinglist/thankyou_message.html'
            else:
                template = 'mailinglist/thankyou.html'
            return render_to_response(template,
                {},
                context_instance=RequestContext(request)
            )
        else:
            status = 400
    else:
        form = SignupForm()
    
    interests = models.InterestItem.objects.all()
    
    if request.is_ajax():
        template = 'mailinglist/signup_form.html'
    else:
        template = 'mailinglist/signup.html'
    
    return HttpResponse(
        render_to_string(template,
            {
                'form': form,
                'interests': interests,
            },
            context_instance=RequestContext(request)
        ),
        status=status,
    )

def mobile_signup(request):
    status = 200
    if request.method == 'POST':
        form = SignupForm(request.POST, initial={'captcha': request.META['REMOTE_ADDR']})
        if form.is_valid():
            form.save()
            template = 'mailinglist/mobile_thankyou.html'
            return render_to_response(template,
                {},
                context_instance=RequestContext(request)
            )
        else:
            HttpResponseRedirect("/signup/mobile/")
    else:
        form = SignupForm()
    
    interests = models.InterestItem.objects.all()
    
    template = 'mailinglist/mobile_signup.html'
    
    return HttpResponse(
        render_to_string(template,
            {
                'form': form,
                'interests': interests,
            },
            context_instance=RequestContext(request)
        ),
        status=status,
    )

templates/mailinglist/mobile_signup.html
{% extends 'base_mobile.html' %}
{% load block_tags %}

{% block title %}{{ block.super }} : Newsletter Sign Up{% endblock %}

{% block body %}
<div class="header">
		<div class="dark_item_top"></div>
		<div class="dark_item_mid_expand">
			<strong>SIGN UP</strong><br />
				To Recieve updates on what's new.<br /><br />
        {% include 'mailinglist/signup_form_mobile.html' %}
    </div>
		<div class="dark_item_base"></div>
	</div>
{% endblock %}


templates/mailinglist/mobile_thankyou.html
{% extends 'base_mobile.html' %}
{% load block_tags %}

{% block title %}{{ block.super }} : Newsletter Sign Up{% endblock %}

{% block body %}
<div class="header">
		<div class="dark_item_top"></div>
		<div class="dark_item_mid_expand">
			<strong>Thank You</strong><br />
<p>Congratulations, you have succesfully subscribed to the newsletter!</p>
    </div>
		<div class="dark_item_base"></div>
	</div>
{% endblock %}


templates/mailinglist/signup.html
{% extends 'base.html' %}
{% load block_tags %}

{% block title %}{{ block.super }} : Newsletter Sign Up{% endblock %}

{% block body %}
    {% include 'mailinglist/signup_form.html' %}
{% endblock %}

templates/mailinglist/signup_form.html
{% regroup interests by group as interests_by_group %}
<form action="{% url signup_form %}" id="signup_form" method="POST" class="signup">
    <fieldset class="left">
        <div class="field">
            {{ form.name.errors }}
            <label for="id_name">Name<em class="required">*</em></label>
            {{ form.name }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Email<em class="required">*</em></label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.dob.errors }}
            <label for="id_dob">DOB</label>
            {{ form.dob }}
        </div>
        <div class="field">
            {{ form.mobile.errors }}
            <label for="id_mobile">Mobile</label>
            {{ form.mobile }}
        </div>
    </fieldset>
    
    <fieldset class="right">
        <div class="field sex"><nobr>{{ form.sex.errors }}</nobr></div>
        <div class="field sex">
            <label for="id_sex">Sex:</label>
            {{ form.sex }}
        </div>
        <div class="field"><nobr>{{ form.interest_items.errors }}</nobr></div>
        {% for group in interests_by_group %}
        <fieldset class="choice_group">
            <legend>{{ group.grouper.title }}</legend>
            <ul>
                {% for item in group.list %}
                <li><label for="id_interest_items_{{ item.pk }}"><input type="checkbox" name="interest_items" value="{{ item.pk }}" id="id_interest_items_{{ item.pk }}" />{{ item.title }}</label></li>
                {% endfor %}
            </ul>
        </fieldset>
        {% endfor %}
    </fieldset>

	<div class="field" id="signup-captcha" style="clear:both;">
	{{ form.captcha }}
	</div>

    <div class="submit">
        <input type="image" src="{{ MEDIA_URL }}images/mailinglist/sign_up_btn.png" value="Send message" alt="sign up" title="sign up" class="nav" />
        <p><em class="required">*</em>Required fields. Providing further details will help us send you information that is more relevant to you!</p>
    </div>
</form>

templates/mailinglist/signup_form_mobile.html
{% regroup interests by group as interests_by_group %}
<form action="/signup/mobile/" id="signup_form" method="POST" class="signup">
    <fieldset class="left">
        <div class="field">
            {{ form.name.errors }}
            <label for="id_name">Name<em class="required">*</em></label>
            {{ form.name }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Email<em class="required">*</em></label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.dob.errors }}
            <label for="id_dob">DOB</label>
            {{ form.dob }}
        </div>
        <div class="field">
            {{ form.mobile.errors }}
            <label for="id_mobile">Mobile</label>
            {{ form.mobile }}
        </div>
    </fieldset>
    
    <fieldset class="right">
        <div class="field sex"><nobr>{{ form.sex.errors }}</nobr></div>
        <div class="field sex">
            <label for="id_sex">Sex:</label>
            {{ form.sex }}
        </div>
        <div class="field"><nobr>{{ form.interest_items.errors }}</nobr></div>
        {% for group in interests_by_group %}
        <fieldset class="choice_group">
            <legend>{{ group.grouper.title }}</legend>
            <ul>
                {% for item in group.list %}
                <li><label for="id_interest_items_{{ item.pk }}"><input type="checkbox" name="interest_items" value="{{ item.pk }}" id="id_interest_items_{{ item.pk }}" />{{ item.title }}</label></li>
                {% endfor %}
            </ul>
        </fieldset>
        {% endfor %}
    </fieldset>

    <div class="submit">
        <input type="image" value="submit" src="{{ MEDIA_URL }}images/mailinglist/sign_up_btn.png" value="Send message" alt="sign up" title="sign up" class="nav" />
        <p><em class="required">*</em>Required fields. Providing further details will help us send you information that is more relevant to you!</p>
    </div>
</form>

templates/mailinglist/thankyou.html
{% extends 'base.html' %}
{% load block_tags %}

{% block title %}{{ block.super }} : Sign Up{% endblock %}

{% block body %}
    {% include 'mailinglist/thankyou_message.html' %}
{% endblock %}

templates/mailinglist/thankyou_message.html
<h2>Thank You</h2>
<p>Congratulations, you have succesfully subscribed to the newsletter!</p>